### ISSUE TITLE
ссылка на названии города

### ISSUE THREAD

**Issue by ctepeo** [coderiver/epronto#11]
В плитках-картинках сделать названия городов ссылкой (положить просто в ссылку)
![image](https://cloud.githubusercontent.com/assets/2236036/6750037/655f86b6-cf07-11e4-9f6a-b20c205fd1e2.png)

**Comment by akella** [comment]
Ну они же и сейчас в ссылке? Что именно нужно сделать? ссылку в ссылке мы сделать не можем же.

**Comment by ctepeo** [comment]
Ссылка будет туда же, куда и ссылка с картинки, то есть это прихоть СЕОшника, для человека будет ссылка по всему блоку.

**Comment by ctepeo** [comment]
![image](https://cloud.githubusercontent.com/assets/2236036/6750400/e1c84384-cf0a-11e4-8771-2433d96d68c6.png)
вот так будет вполне хорошо, # я подменю на норм ссылку. Если бы она не поменяла стиль, я бы сам подставил просто

**Comment by akella** [comment]
То есть по дефолту, у нас будет div вокруг блока, а внутри ссылка на москву, а ты через ЖС потому поменяешь их местами, так?
