### ISSUE TITLE
Центрировать текст в выпадающем меню

### ISSUE THREAD

**Issue by ctepeo** [coderiver/epronto#15]
Центрировать в выпадающих меню цифры. Меню это появляется, если выбрать "Нужно больше номеров или размещение с детьми)

![image](https://cloud.githubusercontent.com/assets/2236036/6798900/a51b8d9a-d222-11e4-84f2-0ca707419352.png)

**Comment by akella** [comment]
Но они вроде и так по центру? или про горизонтальный речь?

**Comment by ctepeo** [comment]
про выпадающий список, там скриншот приложен ;) когда выбираешь кол-во детей/взрослых

**Comment by ctepeo** [comment]
![image](https://cloud.githubusercontent.com/assets/2236036/6799048/bc0fdf32-d223-11e4-9cc3-9f5616972353.png)
вот сюда
