### ISSUE TITLE
Проблемы на старых страницах

### ISSUE THREAD

**Issue by ctepeo** [coderiver/epronto#18]
Например, http://www.epronto.ru/hotels/France/Ile_de_France/Paris/

Шрифт заголовков поменялся 
![image](https://cloud.githubusercontent.com/assets/2236036/7867058/45e5542c-057c-11e5-9027-dc5efbc087cc.png)

На страницах подборок это дало серьезные косяки
http://www.epronto.ru/hotels/France/Ile_de_France/Paris/by_reviews/

![image](https://cloud.githubusercontent.com/assets/2236036/7867077/60558b74-057c-11e5-8403-0f092ed3c4ee.png)

Вот тут еще лучше видно
http://www.epronto.ru/hotels/France/Ile_de_France/Paris/best_deal/
![image](https://cloud.githubusercontent.com/assets/2236036/7867089/7b0ea554-057c-11e5-82f4-728fbe4bc886.png)

**Comment by whats0n** [comment]
можете дать макет? :)

**Comment by ctepeo** [comment]
Ссылка на архив: http://www.epronto.ru/epronto.psd.zip
Пароль на архив у @akella в скайпе

**Comment by akella** [comment]
Насколько я понимаю мы это уже пофиксили? вот скрин сейчас http://take.ms/Dk9QI

**Comment by ctepeo** [comment]
Шрифт пофиксили, теперь бы еще придумать что-нибудь, чтобы названия не расползались (любое длинное название, которое в 2 строки уходит, например: http://www.epronto.ru/hotels/Russia/all/Moscow/poi/ryadom_s_pamyatnikom_mininu_i_pozharskomu/)

**Comment by ctepeo** [comment]
Проблема со шрифтами решена, спасибо. Что делать с обрезанием названий - лучше обсудить в скайпе. Как я понимаю, там работы на 2 минуты, но нужно решение какое-то принять, пусть владелец проекта принимает.
