### ISSUE TITLE
Страница отеля

### ISSUE THREAD

**Issue by ctepeo** [coderiver/epronto#19]
Чтобы ссылки не отдавали 404 в данный момент необходимо авторизироваться в админке (доступы высылал, если необходимо восстановить - в скайп)

http://www.epronto.ru/hotels/France/Ile_de_France/Paris/Hotel_Sunny_Mouffetard/

Проверить были ли в макете такие отступы (визуально кажется, что дофига) 

![image](https://cloud.githubusercontent.com/assets/2236036/7867134/de608532-057c-11e5-9080-13abf7aa6ad6.png)

Блок у карты. Вот тут по идее должно быть до низа + ссылка лифлета лежит поверх этого блока

![image](https://cloud.githubusercontent.com/assets/2236036/7867154/fb706b56-057c-11e5-8248-1dba8308196b.png)

Нет иконки "Для детей"

![image](https://cloud.githubusercontent.com/assets/2236036/7867167/0cab34dc-057d-11e5-8ab5-1b27248dbc07.png)

**Comment by whats0n** [comment]
можете дать макет? :)

**Comment by ctepeo** [comment]
Даем: https://github.com/coderiver/epronto/issues/18#issuecomment-114256275
