### ISSUE TITLE
Изменение структуры карты на странице отеля

### ISSUE THREAD

**Issue by ctepeo** [coderiver/epronto#20]
![image](https://cloud.githubusercontent.com/assets/2236036/7903228/f03441b4-07dd-11e5-879d-6d8a0a98ad2c.png)

Сейчас блок с достопримечательностями (список) лежит в поверх карты (id="map_canvas", width:100%), поэтому при у меня при обращении к карте с методом центрирования появляется не центр (потому что часть карты закрыта блоком):

![image](https://cloud.githubusercontent.com/assets/2236036/7903252/658c2184-07de-11e5-93f5-051bfdbf02fa.png)

То есть сейчас центр считается по отрезкам X, а надо, чтобы был по Y, то есть надо, чтобы блок с картой не заползал под блок со списком

**Comment by valeraderevshukov** [comment]
Готово
