### ISSUE TITLE
Различие с макетом

### ISSUE THREAD

**Issue by ctepeo** [coderiver/epronto#23]
Страница отеля, например

http://www.epronto.ru/hotels/Russia/all/Saint_Petersburg/Alexander_House_Boutique_Hotel/

Название почему-то вылазит за пределы синей плашки, да и в целом получается, что и фоточки не на синей плашке и шапка не такая, как в макете. Скрины:

Есть:

![image](https://cloud.githubusercontent.com/assets/2236036/8627549/89e3a706-2754-11e5-98a2-65cd4ac9b113.png)

Макет:

![image](https://cloud.githubusercontent.com/assets/2236036/8627786/18c3ffec-2756-11e5-8d5e-77c25e43ca0d.png)

**Comment by akella** [comment]
Если на этом типе страниц убрать class="b-inside" то начнет выглядеть как нужно. Вообще все что этот класс делает - меняет позицию голубого фона.

**Comment by akella** [comment]
```
.h-reserv{margin-bottom:15px}
```

**Comment by ctepeo** [comment]
Работает, спасибо
