### ISSUE TITLE
Мобильная версия, форма

### ISSUE THREAD

**Issue by ctepeo** [coderiver/epronto#24]
На странице отеля инпуты в форме поиска по датам неверно отображаются:

![image](https://cloud.githubusercontent.com/assets/2236036/8648056/08861c84-2966-11e5-93dd-79438c347612.png)

**Comment by akella** [comment]
Вот необходимый код:

```
@media only screen and (max-width: 640px){

.form__wrap.form__wrap_h .form .form__date,
.form__wrap.form__wrap_h .form .form__people
{width: auto !important;}
}
```

**Comment by ctepeo** [comment]
Работает, спасибо
