### ISSUE TITLE
Правки по главной

### ISSUE THREAD

**Issue by ctepeo** [coderiver/epronto#4]
Прикрученную версию можно смотреть на 

http://dev.epronto.ru/

http-авторизация:
login:
epronto
password:
zcdjq
1. При наведении на все ссылки и очень важно поля - менять курсор на палец
2. Неправильно сверстали шапку в выпадашках синюю, у нее почему-то есть светлая обводка. Быть не должно

![image](https://cloud.githubusercontent.com/assets/2236036/6727450/110328ea-ce33-11e4-8671-57246b42342e.png)
1. Календарь не по дизайну сделан
2. Когда выбранная дата в календаре вторая, не показывает промежуток выделенным
3. Текстовки на популярных не те шрифты, проверить и привести в соответствие
4. Картинки на промо исправить
5. Не пойму почему, но перед подвалом шрифт кажется тоньше чем в рекомендациях
6. Какго-то фига шрифт заголовка Helvetica. Факап! Везде у нас Open Sans сейчас. Исправить
7. Текст подписи под популярными сделать темнее
8. Везде при наведении подчеркивать ссылки
9. В футере разделители потерялись и поехали между меню. Исправить
10. В футере заменить счетчик (он же настраивается) по цветам как в дизайне
11. Стрелочки на популярные я вышлю отдельно, они не подходят
12. Текст по формой с логотипами, где +50 "Сайтов бронирования" - сделать светлее
13. Потеряли треугольник над блоком +50 Сайтов бронирования

**Comment by akella** [comment]
1-2 - не наша работа
3 - Уже привели
4 Какие картинки и на что исправить? Можно ли актуализировать и уточнить эту правку?
5 Не знаю что сказать на это. У меня на мониторе не кажется
6 Нашли только один заголовок на сайте с Хельветикой, уже его исправили
7 Насколько темнее?
8 Везде - на ссылках которые поверх картинок - тоже подчеркивать? В Навигации основной - подчеркивать? Нужно уточнить
9 Футер сейчас выглядит идентично дизайну, необходимо уточнить что нужно сделать
10 Это полагаю не к нам
11 Стрелочки ок
12
13 Готово

**Comment by ctepeo** [comment]
[x]1-2 - сделал я
[x] 3 - ok
[x] 4 - нужно было исправить позиционирование огромной картинки в блоках, я исправил, в пулл реквесте есть
[x] 5. У меня тоже выглядит как в дизайне

![image](https://cloud.githubusercontent.com/assets/2236036/6749381/9ced45ca-cf00-11e4-931c-e3e38b4eb222.png)

[x] 6 - ok
[?] 7 - переадресуем дизайнеру
[?] 8 - переадресуем дизайнеру
[x] 9 - исправлено мной
[x] 10 - это ко мне, сорри
[+] 11 - не забудьте вмержиться!
[?] 12 - отправить к дизайнеру за уточнением, что значит "светлее", верно?
[x] 13 - спасибо

Итого 7,8,12- уточнять у дизайнера, от вас ждать только 11
