### ISSUE TITLE
Лого обрезается снизу

### ISSUE THREAD

**Issue by ctepeo** [coderiver/epronto#5]
![image](https://cloud.githubusercontent.com/assets/2236036/6727724/4a1fd964-ce35-11e4-8aba-b69b1b364c30.png)

**Comment by akella** [comment]
Не удается повторить, уточните браузер и условия пожалуйста. Страница на скриншоте выглядет зазумленной, так ли это?

**Comment by ctepeo** [comment]
Да, хром виндозный, зазумленная страница, обрезается лого и +50 отелей
